### ISSUE TITLE
Addon folder structure changed - config folder not present in new HAOS-installation

### ISSUE THREAD

**Issue by staanla** [hassio-addons/addon-mqtt-io#101]
As documented [here](https://github.com/home-assistant/developers.home-assistant/pull/1960) just 3 months ago, it seems like the addon-config-mounting-map has recently changed. Unfortunately, I couldn't find the correct commit changing the actual logic.

As a consequence, there seems to be no more "config" folder in newer installations of HAOS:
```
# pwd
/mnt/data/supervisor
# ls
addon_configs       config.json         mounts
addons              dns                 multicast.json
addons.json         dns.json            observer.json
apparmor            emergency           services.json
audio               homeassistant       share
audio.json          homeassistant.json  ssl
backup              ingress.json        tmp
cli.json            media               updater.json
```

Instead, it is recommended to mount "addon_configs". For now I was able to work around this using the share folder and adjusting the addon configuration to search in /share/mqtt-io/config.yml. This could either be reflected as a preferred solution in the corresponding [Documentation](https://github.com/hassio-addons/addon-mqtt-io/blob/1fb155dc86638b5e68c1145b8dfa33f6c980b1c3/mqtt-io/DOCS.md?plain=1#L42) or probably better yet changed in the add-on config. I'm sorry there's no direct PR here, if I get around to it after solving the problem at hand I'd be happy to contribute.

Thanks for your work. I'll be happy to provide more info if necessary.

**Comment by sinclairpaul** [comment]
The path is relevant to the container, not the filesystem on disk.  The default location on disk is within the addons/data folder which hasn't changed.
