### ISSUE TITLE
addon didn't start - config file missing 

### ISSUE THREAD

**Issue by dkotte** [hassio-addons/addon-mqtt-io#110]
Until now, all within HA is done from GUI
While starting iqtt-io i got the message like "Config file is missing ... create the config /config/mqtt-io/config.yml"
Is there an option to build these file from GUI?

Thx Dirk

**Comment by kristianschneider** [comment]
@dkotte 
You probably want to use the File editor addon. [https://github.com/home-assistant/addons/tree/master/configurator](https://github.com/home-assistant/addons/tree/master/configurator)

create the mqtt-io folder and then the config.yml file
