### ISSUE TITLE
RPI4 RuntimeError: Unknown platform.

### ISSUE THREAD

**Issue by LukasFrinn** [hassio-addons/addon-mqtt-io#133]
Hi,

I have a homeassistant on a raspberry pi 4 and I want to use this addon to read temperature and humidity with a DHT22 sensor. But from what I have read, there is no support for RPI4 in the older version of the adafruit library. 
More is written about it here: https://stackoverflow.com/questions/64093805/adafruit-python-dht-raspberry-pi-in-get-platform-runtimeerror-unknown-platf

LOG:
File "/usr/lib/python3.11/site-packages/Adafruit_DHT/common.py", line 63, in get_platform
    raise RuntimeError('Unknown platform.')
RuntimeError: Unknown platform.

**Comment by sinclairpaul** [comment]
The addon installs the upstream software, so as it's not supported there isn't much to be done here.
