### ISSUE TITLE
[Feature] Server & username & password automatic detection

### ISSUE THREAD

**Issue by mahnunchik** [hassio-addons/addon-mqtt-io#134]
# Problem/Motivation

It would be really great to have automatic detection of `server` & `username` & `password` for local mosquitto installation.

## Expected behavior

Like in `Zigbee2MQTT`:

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/6d5d0e5fd3b37c840a3b218814905914fa3c1e5f/common/rootfs/docker-entrypoint.sh#L89-L100

## Actual behavior

Manual configuration

**Comment by sinclairpaul** [comment]
As the config is managed through a manually created file, not sure how this would be possible?

**Comment by mahnunchik** [comment]
@sinclairpaul You may find how it is implemented in Zigbee2MQTT https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/6d5d0e5fd3b37c840a3b218814905914fa3c1e5f/common/rootfs/docker-entrypoint.sh#L89-L100

**Comment by sinclairpaul** [comment]
Thanks I'm aware, and it's passed through Environment Variables, this application has a file managed by the user.

**Comment by mahnunchik** [comment]
Yes, and if server/username/password not specified by the user then it consumed from the env vars. It is super helpful (end easy to use) for *simple* setup like mosquitto, mqtt and mqtt-io on the same machine.

**Comment by sinclairpaul** [comment]
Which is due to the fact that the application supports configuration via Environment Variables, this doesn't.  You can look at the MQTT IO documentation for reference which this addon installs.

**Comment by mahnunchik** [comment]
I've added support for the environment variables https://github.com/flyte/mqtt-io?tab=readme-ov-file#execution

**Comment by mahnunchik** [comment]
@sinclairpaul mqtt-io supports environment variables now and host/user/pass discovery approach can be implemented 😉

**Comment by mahnunchik** [comment]
Initial config can be created on first run:

```bash
if ! bashio::fs.file_exists "${configuration_file}"; then
    mkdir -p "$(dirname $configuration_file)" || bashio::exit.nok "Could not create $configuration_file"
    cat <<EOF > "$configuration_file"
mqtt:
  topic_prefix: mqtt_io
  ha_discovery:
    enabled: yes
EOF
fi
```

https://github.com/hassio-addons/addon-mqtt-io/blob/main/mqtt-io/rootfs/etc/s6-overlay/s6-rc.d/mqtt-io/run#L10-L24

**Comment by mahnunchik** [comment]
@sinclairpaul @frenck @thecode @mrk-its I need help with parsing yaml configuration to pass environment variables only if user does not pass the host/user/pass in the manually created configuration.

**Comment by mahnunchik** [comment]
This improvement stops similar issues like https://github.com/hassio-addons/addon-mqtt-io/issues/142 https://github.com/hassio-addons/addon-mqtt-io/issues/115 https://github.com/hassio-addons/addon-mqtt-io/issues/110
